name: Nightly Tests

# CI/CD disabled for portfolio demonstration
# on:
#   schedule:
#     - cron: '0 1 * * 1-5'  # will run at 1 AM, Monday through Friday

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: python3 -m playwright install --with-deps

      - name: Run tests
        run: make run-all-tests
